name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '* * * * 0'

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: docker://replicated/dockerfilelint:latest
        with:
          args: Dockerfile

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: haxorof/openstack-cli
          tag_with_sha: false
          add_git_labels: true
          tags: latest
          push: ${{ endsWith(github.ref, '/master') }}
